#server:
#  port: 8888

google:
  client:
    clientId: <GOOGLE_CLIENT_ID>
    clientSecret: <GOOGLE_SECRET>
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - openid
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true

facebook:
  client:
    clientId: <FACEBOOK_CLIENT_ID>
    clientSecret: <FACEBOOK_SECRET>
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: <GITHUB_CLIENT_ID>
    clientSecret: <GITHUB_SECRET>
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

CLIENT_URL: http://localhost:4200
HEADERS: Content-Type,Content-Length,Connection,Date,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Access-Control-Allow-Credentials,Content-Encoding,Vary,X-Cache,Via,X-XSRF-TOKEN,Authorization,Origin
METHODS: GET,POST,PUT,OPTIONS,DELETE

logging:
  level:
    org.springframework.security: DEBUG
